PLUGIN_NAME=		gatus
PLUGIN_VERSION=		1.0
PLUGIN_COMMENT=		Developer-oriented health dashboard
PLUGIN_DEPENDS=		gatus
PLUGIN_MAINTAINER=	daniel@example.com
PLUGIN_WWW=		https://github.com/TwiN/gatus

.include "../../Mk/plugins.mk"
